export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',
    GETALLUSER_SUCCESS: 'USERS_GETALLUSER_SUCCESS',

    ADDPOST_REQUEST: 'USERS_ADDPOST_REQUEST',
    ADDPOST_SUCCESS: 'USERS_ADDPOST_SUCCESS',
    ADDPOST_FAILURE: 'USERS_ADDPOST_FAILURE',

    ADDCOMMENT_SUCCESS: 'USERS_ADDCOMMENT_SUCCESS',
    ADDCOMMENT_REQUEST: 'USERS_ADDCOMMENT_REQUEST',

    DELETEPOST_SUCCESS:'USERS_DELETEPOST_SUCCESS',

    GETALLUSERS_SUCCESS:'USERS_GETALLUSERS_SUCCESS'
};
